"""Generate telemetry dashboard as markdown."""
import os
from datetime import datetime


def generate_dashboard(snapshot, output_path=None):
    """Create a formatted markdown dashboard from a telemetry snapshot.

    Args:
        snapshot: Dict from TelemetryEngine.collect_snapshot().
        output_path: Optional path to write the markdown file.

    Returns:
        Markdown string of the dashboard.
    """
    lines = []
    lines.append("# LitigationOS Telemetry Dashboard")
    lines.append(f"**Generated:** {snapshot['timestamp']}")
    lines.append(f"**Separation:** {snapshot['separation_days']} days")
    lines.append("")

    # --- System metrics ---
    sys_m = snapshot.get("system", {})
    lines.append("## System Resources")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")
    lines.append(f"| CPU | {sys_m.get('cpu_percent', '?')}% |")
    mem_used = sys_m.get("memory_used_gb", "?")
    mem_total = sys_m.get("memory_total_gb", "?")
    mem_pct = sys_m.get("memory_percent", "?")
    lines.append(f"| Memory | {mem_used}/{mem_total} GB ({mem_pct}%) |")
    disk_free = sys_m.get("disk_c_free_gb", "?")
    disk_pct = sys_m.get("disk_c_percent", 0)
    try:
        free_pct = f"{100 - float(disk_pct):.0f}"
    except (TypeError, ValueError):
        free_pct = "?"
    lines.append(f"| C: Drive Free | {disk_free} GB ({free_pct}% free) |")

    # Additional drives
    for letter in ["d", "f", "g", "i", "j"]:
        key = f"disk_{letter}_free_gb"
        if key in sys_m:
            lines.append(
                f"| {letter.upper()}: Drive Free | {sys_m[key]} GB |"
            )
    lines.append("")

    # --- Database metrics ---
    db_m = snapshot.get("database", {})
    lines.append("## Database Status")
    lines.append("")
    lines.append("| Table | Rows |")
    lines.append("|-------|------|")
    table_keys = [
        "evidence_quotes",
        "authority_chains",
        "timeline_events",
        "impeachment_matrix",
        "contradictions",
        "judicial_violations",
    ]
    for key in table_keys:
        val = db_m.get(key, 0)
        lines.append(f"| {key} | {val:,} |")

    db_size = db_m.get("db_size_mb", 0)
    wal_size = db_m.get("wal_size_mb", 0)
    table_count = db_m.get("table_count", 0)
    lines.append(f"| **DB Size** | {db_size:.0f} MB |")
    lines.append(f"| **WAL Size** | {wal_size:.1f} MB |")
    lines.append(f"| **Total Tables** | {table_count:,} |")
    lines.append("")

    # --- Filing status ---
    filing = snapshot.get("filing", {})
    deadlines = filing.get("upcoming_deadlines", [])
    if deadlines:
        lines.append("## Upcoming Deadlines")
        lines.append("")
        lines.append("| Filing | Due | Status |")
        lines.append("|--------|-----|--------|")
        for d in deadlines:
            lines.append(f"| {d['title']} | {d['due']} | {d['status']} |")
        lines.append("")

    total_filings = filing.get("total_filings", 0)
    if total_filings:
        lines.append(f"**Total filing packages:** {total_filings}")
        lines.append("")

    # --- Evidence coverage ---
    ev = snapshot.get("evidence", {})
    by_lane = ev.get("by_lane", {})
    if by_lane:
        lines.append("## Evidence by Lane")
        lines.append("")
        lines.append("| Lane | Count |")
        lines.append("|------|-------|")
        for lane, count in by_lane.items():
            lines.append(f"| {lane} | {count:,} |")
        lines.append("")

    by_cat = ev.get("by_category", {})
    if by_cat:
        lines.append("## Evidence by Category")
        lines.append("")
        lines.append("| Category | Count |")
        lines.append("|----------|-------|")
        for cat, count in by_cat.items():
            lines.append(f"| {cat} | {count:,} |")
        lines.append("")

    # --- Engine status ---
    eng = snapshot.get("engines", {})
    eng_count = eng.get("count", 0)
    lines.append(f"## Engines ({eng_count} detected)")
    lines.append("")
    engine_list = eng.get("engines", {})
    if engine_list:
        lines.append("| Engine | Status |")
        lines.append("|--------|--------|")
        for name, info in engine_list.items():
            status = "✅ Ready" if info.get("has_init") else "⚠️ No init"
            lines.append(f"| {name} | {status} |")
        lines.append("")

    # --- Footer ---
    lines.append("---")
    lines.append(
        f"*Dashboard generated by TelemetryEngine v1.0.0 at "
        f"{snapshot['timestamp']}*"
    )

    report = "\n".join(lines)

    if output_path:
        out_dir = os.path.dirname(output_path)
        if out_dir:
            os.makedirs(out_dir, exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(report)

    return report
