"""Generate markdown sync reports from BrainSyncEngine status data."""

import os
from datetime import datetime
from pathlib import Path


def generate_sync_report(
    sync_status: dict,
    output_path: str | Path | None = None,
) -> str:
    """Convert a ``sync_status()`` dict into a Markdown report.

    Parameters
    ----------
    sync_status : dict
        Output of :meth:`BrainSyncEngine.sync_status`.
    output_path : str or Path, optional
        If given, the report is also written to this file.

    Returns
    -------
    str
        The Markdown report text.
    """
    lines: list[str] = [
        "# Brain Sync Report",
        "",
        f"**Generated:** {sync_status['timestamp']}",
        "",
        f"## Central DB — {sync_status['central_db']['tables']} tables",
        f"Path: `{sync_status['central_db']['path']}`",
        "",
    ]

    total_mismatches = sync_status.get("summary", {}).get("total_mismatches", "?")
    total_brains = sync_status.get("summary", {}).get("total_brains", len(sync_status["brains"]))
    lines.append(f"**Brains scanned:** {total_brains} | **Total mismatches:** {total_mismatches}")
    lines.append("")
    lines.append("---")
    lines.append("")

    for brain in sync_status["brains"]:
        lines.append(f"### {brain['name']} ({brain['size_mb']} MB)")

        if "error" in brain:
            lines.append(f"- ❌ Error: {brain['error']}")
            lines.append("")
            continue

        lines.append(f"- Tables: {brain['tables']} ({brain['common_with_central']} shared with central)")

        mismatches = brain.get("mismatches", [])
        if mismatches:
            lines.append(f"- **⚠️ {len(mismatches)} row-count mismatches:**")
            lines.append("")
            lines.append("| Table | Central | Brain | Delta |")
            lines.append("|-------|---------|-------|-------|")
            for m in mismatches[:20]:
                lines.append(
                    f"| `{m['table']}` | {m['central']:,} | {m['brain']:,} | {m['delta']:+,} |"
                )
            if len(mismatches) > 20:
                lines.append(f"| ... | ... | ... | *{len(mismatches) - 20} more* |")
        else:
            lines.append("- ✅ No row-count mismatches")

        unique = brain.get("unique_tables", [])
        if unique:
            shown = unique[:15]
            suffix = f" (+{len(unique) - 15} more)" if len(unique) > 15 else ""
            lines.append(f"- Unique tables: `{'`, `'.join(shown)}`{suffix}")

        lines.append("")

    lines.append("---")
    lines.append(f"*Report generated by brain_sync engine v1.0.0 at {datetime.now():%Y-%m-%d %H:%M}*")

    report = "\n".join(lines)

    if output_path:
        out = Path(output_path)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(report, encoding="utf-8")

    return report
